Repository mdsreq-fga-unb/2025.1-T01-CapitalNexus, pull requests merged in 2025-05, with the labels that each got.

#7 Refatorando o texto de 'Objetivo do Produto'
  docs/visao/solucao.md
Labels: documentation, improvement

#10 :memo: Correlacionando objetivos do projeto com objetivos específicos…
  docs/visao/solucao.md
Labels: documentation, improvement

#19 build: secret key agora lê do .env
  capital_nexus/settings.py
  requirements.txt
Labels: requirements

#31 docs(atividades-er): adicionando seção de engenharia de requisitos (técnicas, tabela e relações)
  .gitignore
  docs/visao/engrequisitos.md
Labels: documentation, enhancement

#39 [PR] Configurando ambiente
  capital_nexus/settings.py
  capital_nexus/urls.py
  docker-compose.yml
  members/__init__.py
  members/admin.py
  members/apps.py
  members/migrations/__init__.py
  members/models.py
  members/tests.py
  members/urls.py
  members/views.py
  public/__init__.py
  public/admin.py
  public/apps.py
  public/migrations/__init__.py
  public/models.py
  public/tests.py
  public/urls.py
  public/views.py
  requirements.txt
Labels: environment
